const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),{EventEmitter}=require('node:events'),Sessions=require('../bridge/event-sessions.cjs');
const ID='10000000-0000-4000-8000-000000000001';
test('provisional user bubble is replaced by the acknowledged message ID',async t=>{const {stream,sessions}=setup(t);stream.push({...stream.state,turns:[...stream.state.turns,{id:'fallback-turn-0:0:user',role:'user',text:'hello'}]});stream.push({...stream.state,turns:[{id:'old-user',role:'user',text:'old'},{id:'old-answer',role:'assistant',text:'old answer'},{id:'server-id:0:user',role:'user',text:'hello'}]});assert.equal(sessions.history.get(ID).turns.filter(t=>t.text==='hello').length,1);assert.equal(sessions.history.get(ID).turns.at(-1).id,'server-id:0:user');});
function setup(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'paper-event-state-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));const stream=new EventEmitter();stream.state={title:'Fixture',threadId:ID,inPaper:true,draft:'',sending:false,turns:[{id:'old-user',role:'user',text:'old'},{id:'old-answer',role:'assistant',text:'old answer'}]};stream.read=async()=>stream.state;stream.open=async()=>stream.state;stream.draft=async()=>{};stream.push=s=>{stream.state=s;stream.emit('snapshot',s);};return{stream,sessions:new Sessions(dir,stream)};}
test('virtualized messages: a new message ID completes even when user count stays constant',async t=>{const {stream,sessions}=setup(t),c=sessions.register({mode:'blank'});sessions.bindings[sessions.context(c.id).key]={threadId:ID,title:'Fixture',phase:'ready'};stream.submit=async text=>{stream.push({...stream.state,sending:true,turns:[{id:'new-user',role:'user',text}]});setImmediate(()=>stream.push({...stream.state,sending:false,turns:[...stream.state.turns,{id:'new-answer',role:'assistant',text:'OK'}]}));};const result=await sessions.send(c.id,'new question');assert.equal(result.phase,'ready');assert.equal(sessions.transcript(c.id).turns.length,4);});
test('first chat persists cloud identity when local draft identity changes during generation',async t=>{const {stream,sessions}=setup(t),c=sessions.register({mode:'blank'}),local='local-chatgpt:20000000-0000-4000-8000-000000000002';stream.newChat=async()=>{stream.state={...stream.state,threadId:local,localThreadId:local,newPaper:true,turns:[]};return stream.state;};stream.submit=async text=>{stream.push({...stream.state,newPaper:false,sending:true,turns:[{id:'new-user',role:'user',text}]});setImmediate(()=>{stream.push({...stream.state,threadId:ID,sending:true,turns:[...stream.state.turns,{id:'new-answer',role:'assistant',text:'OK'}]});stream.push({...stream.state,sending:false});});};const result=await sessions.send(c.id,'hello');const b=sessions.bindings[sessions.context(c.id).key];assert.equal(b.threadId,ID);assert.equal(b.localId,local);assert.equal(result.phase,'ready');assert.equal(result.uploaded,false);});
test('lost connection after submission persists uncertainty and does not replay',async t=>{const {stream,sessions}=setup(t),c=sessions.register({mode:'blank'});sessions.bindings[sessions.context(c.id).key]={threadId:ID,title:'Fixture',phase:'ready'};let sends=0;stream.submit=async()=>{sends++;setImmediate(()=>stream.emit('disconnected'));};await assert.rejects(sessions.send(c.id,'hello'),/断开/);await assert.rejects(sessions.send(c.id,'hello'),/尚未确认/);assert.equal(sends,1);assert.equal(sessions.info(c.id).phase,'uncertain');});
test('confirmed recovery reads the original answer without resubmitting',async t=>{const {stream,sessions}=setup(t),c=sessions.register({mode:'blank'});sessions.bindings[sessions.context(c.id).key]={threadId:ID,title:'Fixture',phase:'uncertain',pendingPrompt:'hello'};let sends=0;stream.submit=()=>{sends++;};await assert.rejects(sessions.recover(c.id),/未确认/);stream.push({...stream.state,turns:[{id:'u',role:'user',text:'hello'},{id:'a',role:'assistant',text:'finished'}]});assert.equal((await sessions.recover(c.id)).phase,'ready');assert.equal(sends,0);});
test('subsequent attachments are passed to the same conversation before submit',async t=>{const {stream,sessions}=setup(t),c=sessions.register({mode:'blank'});sessions.bindings[sessions.context(c.id).key]={threadId:ID,title:'Fixture',phase:'ready'};const order=[];stream.attach=async file=>order.push(file);stream.submit=async text=>{order.push('send');stream.push({...stream.state,sending:true,turns:[{id:'u',role:'user',text}]});setImmediate(()=>stream.push({...stream.state,sending:false,turns:[...stream.state.turns,{id:'a',role:'assistant',text:'done'}]}));};await sessions.send(c.id,'question',()=>{},['one.txt','two.txt']);assert.deepEqual(order,['one.txt','two.txt','send']);assert.equal(sessions.bindings[sessions.context(c.id).key].threadId,ID);});
