const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),http=require('node:http'),{spawn}=require('node:child_process');
const AppStream=require('../bridge/app-stream.cjs'),EventSessions=require('../bridge/event-sessions.cjs');
const wait=ms=>new Promise(r=>setTimeout(r,ms));
async function until(check){for(let i=0;i<150;i++){if(await check())return;await wait(40);}throw Error('Test page did not reach expected state');}
test('real CDP: DOM events, background input, model menu, and no duplicate sends',async t=>{
  const root=fs.mkdtempSync(path.join(os.tmpdir(),'paper-cdp-test-')),profile=path.join(root,'browser');
  let app,browser;
  const html=`<!doctype html><meta charset="utf-8"><title>Paper fixture</title>
  <div data-app-action-sidebar-thread-id="00000000-0000-4000-8000-000000000001" data-app-action-sidebar-thread-kind="chatgpt" data-app-action-sidebar-thread-selected="true"></div>
  <main><button>项目：Paper</button><section id="turns"><div data-chatgpt-conversation-turn><h2>你说：</h2><p>old</p><h2>ChatGPT 说：</h2><p data-markdown-text-style="assistant-message">old answer</p></div></section>
  <div contenteditable="true" aria-label="给 ChatGPT 发消息" id="editor"></div><button id="send">发送</button><div id="activity"></div>
  <button id="model">选择 ChatGPT 模型</button><div id="menu"></div></main>
  <script>window.selectedModel="Fixture A";window.sentCount=0;window.mutationTimes=[];send.onclick=()=>{window.sentCount++;let q=editor.innerText;editor.innerText='';let turn=document.createElement('div');turn.setAttribute('data-chatgpt-conversation-turn','');let h=document.createElement('h2');h.textContent='你说：';let p=document.createElement('p');p.textContent=q;let a=document.createElement('h2');a.textContent='ChatGPT 说：';let reply=document.createElement('p');reply.setAttribute('data-markdown-text-style','assistant-message');turn.append(h,p,a,reply);turns.append(turn);activity.innerHTML='<button>停止</button>';let i=0;const timer=setInterval(()=>{mutationTimes.push(Date.now());reply.textContent+='文本'+(++i);if(i===12){clearInterval(timer);activity.innerHTML='';}},30);};
  model.onclick=()=>{menu.setAttribute('role','menu');menu.innerHTML='<div role="menuitem">高，第 3 项，共 5 项。</div><button role="menuitem" id="choose">选择模型</button>';choose.onclick=()=>{menu.replaceChildren();for(const label of ['Fixture A','Fixture B']){const item=document.createElement('button');item.setAttribute('role','radio');item.setAttribute('aria-checked',String(window.selectedModel===label));item.textContent=label;item.onclick=()=>{window.selectedModel=label;menu.innerHTML='';};menu.append(item);}};};document.addEventListener('keydown',e=>{if(e.key==='Escape')menu.innerHTML='';});</script>`;
  let uiStrength=1,uiSends=0,uiFiles=[];const uiModels=()=>({models:[{name:'Fixture model',selected:true,enabled:true}],strength:'Medium',power:{index:uiStrength,max:4,options:['Instant','Medium','High','XHigh','Pro'].map(label=>({label}))}});
  const server=http.createServer(async(req,res)=>{const url=new URL(req.url,'http://localhost');if(url.pathname.startsWith('/api/')){const chunks=[];for await(const c of req)chunks.push(c);const raw=Buffer.concat(chunks);let b={};if(req.headers['content-type']?.includes('json'))b=JSON.parse(raw.toString()||'{}');res.setHeader('Content-Type','application/json');if(url.pathname==='/api/upload')return res.end(JSON.stringify({id:'file-one',name:url.searchParams.get('name'),size:raw.length}));if(url.pathname==='/api/session/config'){uiStrength=b.index;return res.end(JSON.stringify(uiModels()));}if(url.pathname==='/api/session/model')return res.end(JSON.stringify(uiModels()));if(url.pathname==='/api/transcript')return res.end(JSON.stringify({turns:[]}));if(url.pathname==='/api/session/send-stream'){uiSends++;uiFiles=b.files;res.setHeader('Content-Type','application/x-ndjson');return res.end([{type:'accepted'},{type:'snapshot',turns:[{role:'user',text:b.text},{role:'assistant',text:'Final only'}],generating:false},{type:'complete',info:{mode:'blank',phase:'ready'}}].map(x=>JSON.stringify(x)).join('\n')+'\n');}return res.end(JSON.stringify({mode:'blank',phase:'ready',draftKey:'fixture-ui'}));}
    const asset={'/ui':'index.html','/client.js':'client.js','/style.css':'style.css','/stream.js':'stream.js'}[url.pathname];if(asset){res.setHeader('Content-Type',asset.endsWith('.js')?'text/javascript':asset.endsWith('.css')?'text/css':'text/html; charset=utf-8');return res.end(fs.readFileSync(path.join(__dirname,'../bridge',asset)));}res.setHeader('Content-Type','text/html; charset=utf-8');res.end(html);});await new Promise(r=>server.listen(0,'127.0.0.1',r));
  t.after(async()=>{await app?.cdp.call('Browser.close').catch(()=>{});await app?.close().catch(()=>{});server.close();if(browser&&browser.exitCode===null){browser.kill();await new Promise(r=>{browser.once('exit',r);setTimeout(r,2000);});}for(let i=0;i<20;i++){try{fs.rmSync(root,{recursive:true,force:true});break;}catch{await wait(200);}}assert.equal(fs.existsSync(root),false,'temporary browser profile released');});
  browser=spawn('C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe',['--headless=new','--remote-debugging-port=0','--remote-debugging-address=127.0.0.1','--no-first-run','--disable-background-networking','--disable-sync',`--user-data-dir=${profile}`,`http://127.0.0.1:${server.address().port}`],{windowsHide:true,stdio:'ignore'});
  let port;for(let i=0;i<100;i++){try{port=Number(fs.readFileSync(path.join(profile,'DevToolsActivePort'),'utf8').split('\n')[0]);if(port)break;}catch{}await wait(100);}assert.ok(port,'isolated browser started');
  const targets=await(await fetch(`http://127.0.0.1:${port}/json/list`)).json(),target=targets.find(t=>t.url.startsWith(`http://127.0.0.1:${server.address().port}`));assert.ok(target);
  app=new AppStream();await assert.rejects(app.connect(target),/只能连接/);
  // Test fixture connects explicitly; production discovery accepts app:// pages only.
  await app.cdp.connect(target.webSocketDebuggerUrl);await until(()=>app.cdp.evaluate('document.readyState==="complete"&&!!document.getElementById("editor")'));await app.observe();assert.equal((await app.read()).threadId,'00000000-0000-4000-8000-000000000001');
  const sessions=new EventSessions(root,app);sessions.bindings['paper:fixture']={title:'Paper fixture',threadId:'00000000-0000-4000-8000-000000000001',uploaded:true,phase:'ready'};
  const c=sessions.register({mode:'paper',key:'fixture',title:'Paper fixture',pdfPath:path.join(root,'fixture.pdf')});
  await app.cdp.evaluate('(()=>{const u=document.createElement("div");u.setAttribute("data-content-search-unit-key","thinking-only:assistant");u.textContent="PRIVATE THOUGHT";document.querySelector("main").append(u)})()');assert.equal((await app.read()).turns.some(t=>t.text.includes('PRIVATE THOUGHT')),false);await app.cdp.evaluate('document.querySelector("[data-content-search-unit-key]").remove()');
  await sessions.open(c.id);assert.equal(await app.cdp.evaluate('sentCount'),0);
  const models=await sessions.model(c.id);assert.equal(models.models.length,2);assert.equal(models.models[0].selected,true);const switched=await app.model('Fixture B');assert.equal(switched.models.find(m=>m.selected).name,'Fixture B');assert.equal(await app.cdp.evaluate('sentCount'),0);
  const events=[],arrival=[];const info=await sessions.send(c.id,'你好 流式测试',e=>{events.push(e);if(e.type==='snapshot'&&e.turns.at(-1)?.role==='assistant')arrival.push(Date.now());});
  assert.equal(info.transport,'app-dom-events');assert.equal(await app.cdp.evaluate('sentCount'),1);assert.equal(sessions.info(c.id).phase,'ready');assert.ok(events.filter(e=>e.type==='snapshot').length>=8,'incremental events are pushed');assert.match(events.at(-1).turns.at(-1).text,/文本12$/);
  const changes=await app.cdp.evaluate('mutationTimes'),latencies=arrival.map((at,i)=>at-changes[Math.min(i,changes.length-1)]).filter(x=>x>=0);
  console.log(JSON.stringify({source:'isolated local Edge fixture, not ChatGPT',changes:changes.length,received:arrival.length,medianEventMs:latencies.sort((a,b)=>a-b)[Math.floor(latencies.length/2)]}));
  // Switching the App page must not erase previously received paper history.
  await app.cdp.evaluate('document.querySelector("[data-app-action-sidebar-thread-id]").setAttribute("data-app-action-sidebar-thread-selected","false");document.querySelector("main button").textContent="项目：Other"');await wait(30);assert.match(sessions.transcript(c.id).turns.at(-1).text,/文本12$/);
  await app.cdp.call('Page.navigate',{url:'http://127.0.0.1:'+server.address().port+'/ui?context=fixture#test-token'});
  for(let i=0;i<100;i++){if(await app.cdp.evaluate('!!document.getElementById("send")&&!document.getElementById("send").disabled'))break;await wait(30);}
  assert.equal(await app.cdp.evaluate('document.getElementById("send").disabled'),false);assert.equal(uiSends,0,'opening does not send');
  assert.equal(await app.cdp.evaluate('document.getElementById("model").getBoundingClientRect().top>=document.getElementById("prompt").getBoundingClientRect().bottom'),true,'models below input');
  await app.cdp.evaluate('document.dispatchEvent(new WheelEvent("wheel",{ctrlKey:true,deltaY:-100,bubbles:true,cancelable:true}))');
  assert.equal(await app.cdp.evaluate('document.getElementById("zoomReset").textContent'),'105%');
  await app.cdp.call('Page.reload');for(let i=0;i<100;i++){if(await app.cdp.evaluate('!!document.getElementById("send")&&!document.getElementById("send").disabled'))break;await wait(30);}
  assert.equal(await app.cdp.evaluate('document.getElementById("zoomReset").textContent'),'105%');
  await app.cdp.evaluate('document.getElementById("power").dispatchEvent(new WheelEvent("wheel",{deltaY:-100,bubbles:true,cancelable:true}))');await until(async()=>uiStrength===2&&await app.cdp.evaluate('!document.getElementById("power").disabled'));assert.equal(uiStrength,2);
  await app.cdp.evaluate('(()=>{const dt=new DataTransfer();dt.items.add(new File(["synthetic content"],"extra.txt",{type:"text/plain"}));document.dispatchEvent(new DragEvent("drop",{dataTransfer:dt,bubbles:true,cancelable:true}));})()');await until(()=>app.cdp.evaluate('document.getElementById("files").children.length===1&&!document.getElementById("send").disabled'));
  assert.equal(await app.cdp.evaluate('document.getElementById("files").textContent'),'extra.txt ×');assert.equal(uiSends,0,'drop alone does not send');
  await app.cdp.evaluate('document.getElementById("prompt").value="hello";document.getElementById("prompt").dispatchEvent(new KeyboardEvent("keydown",{key:"Enter",bubbles:true,cancelable:true}))');await until(()=>app.cdp.evaluate('document.getElementById("messages").textContent.includes("Final only")&&document.getElementById("prompt").value===""'));
  assert.equal(uiSends,1);assert.deepEqual(uiFiles,['file-one']);assert.match(await app.cdp.evaluate('document.getElementById("messages").textContent'),/Final only/);assert.equal(await app.cdp.evaluate('document.getElementById("prompt").value'),'');

});
