const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),vm=require('node:vm'),{spawn}=require('node:child_process'),Owners=require('../bridge/owners.cjs');
const wait=ms=>new Promise(r=>setTimeout(r,ms));
test('runtime leaves virtualized AppData and migrates bindings without overwriting newer settings',t=>{
  const root=fs.mkdtempSync(path.join(os.tmpdir(),'localchat-migrate-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));const local=path.join(root,'old-local'),home=path.join(root,'home'),old=path.join(local,'ZoteroLocalChat');fs.mkdirSync(old,{recursive:true});fs.writeFileSync(path.join(old,'papers.json'),JSON.stringify({fixture:{threadId:'existing',uploaded:true}}),'utf8');fs.writeFileSync(path.join(old,'settings.json'),JSON.stringify({project:'Paper'}),'utf8');
  const run=()=>require('node:child_process').execFileSync(process.execPath,['-e','process.stdout.write(require('+JSON.stringify(path.join(__dirname,'../bridge/runtime.cjs'))+')())'],{env:{...process.env,LOCALAPPDATA:local,USERPROFILE:home,HOME:home},encoding:'utf8',windowsHide:true});const current=run();assert.equal(current,path.join(home,'.zotero-localchat'));assert.equal(fs.readFileSync(path.join(current,'papers.json'),'utf8'),fs.readFileSync(path.join(old,'papers.json'),'utf8'));fs.writeFileSync(path.join(current,'settings.json'),JSON.stringify({project:'Custom'}),'utf8');run();assert.equal(JSON.parse(fs.readFileSync(path.join(current,'settings.json'),'utf8')).project,'Custom');assert.equal(fs.existsSync(path.join(current,'endpoint.json')),false,'stale endpoint is not migrated');
});
test('bridge lifetime follows its attached Zotero processes and preserves an active response',()=>{const alive=new Set([101,102]),o=new Owners(pid=>alive.has(pid));assert.equal(o.shouldStop(false),false);assert.throws(()=>o.add(404));o.add(101);o.add(102);alive.delete(101);assert.equal(o.shouldStop(false),false);alive.delete(102);assert.equal(o.shouldStop(true),false);assert.equal(o.shouldStop(false),true);});
test('Zotero starts a missing or dead bridge once, without launching ChatGPT',async()=>{
  for(const stale of [false,true]){
    const files=new Map(),root='C:\\Fixture\\.zotero-localchat',url='http://127.0.0.1:23128/#'+'a'.repeat(64);let running=false,launches=0,owners=0,options;
    files.set(path.win32.join(root,'launcher.json'),{node:'C:\\Node\\node.exe',server:'C:\\Plugin\\bridge\\server.cjs'});if(stale)files.set(path.win32.join(root,'endpoint.json'),{url});
    const sandbox={URL,PathUtils:path.win32,Components:{interfaces:{nsIFile:{}}},IOUtils:{exists:async f=>files.has(f)||['C:\\Node\\node.exe','C:\\Plugin\\bridge\\server.cjs'].includes(f),readJSON:async f=>files.get(f)},Services:{dirsvc:{get:()=>({path:'C:\\Fixture'})},appinfo:{processID:101}},ChromeUtils:{importESModule:()=>({Subprocess:{call:async o=>{launches++;options=o;running=true;files.set(path.win32.join(root,'endpoint.json'),{url});return{stdout:{readString:async()=>''},wait:async()=>({exitCode:0})};}}})},Zotero:{initializationPromise:Promise.resolve(),Promise:{delay:async()=>{}},Reader:{registerEventListener(){}},getMainWindows:()=>[],getMainWindow:()=>({AbortSignal,fetch:async(u,options)=>{assert.ok(u.startsWith('http://127.0.0.1:23128/'));if(!running)throw Error('connection refused');if(u.endsWith('/api/owner')){assert.equal(JSON.parse(options.body).pid,101);owners++;}return{ok:true};}}),logError:e=>{throw e;}}};
    vm.createContext(sandbox);vm.runInContext(fs.readFileSync(path.join(__dirname,'../addon/bootstrap.js'),'utf8'),sandbox);await sandbox.startup({rootURI:'file:///fixture/'});
    await Promise.all([sandbox.Mirror.endpoint(),sandbox.Mirror.endpoint()]);assert.equal(launches,1);assert.equal(owners,1);assert.equal(options.command,'C:\\Node\\node.exe');assert.deepEqual(Array.from(options.arguments),['C:\\Plugin\\bridge\\server.cjs','--zotero-pid','101']);await sandbox.Mirror.endpoint();assert.equal(launches,1,'healthy bridge is reused');
    running=false;await sandbox.Mirror.endpoint();assert.equal(launches,2,'manual reconnect restarts a dead bridge');
  }
});
test('real bridge exits and removes its endpoint after its Zotero owner exits',async t=>{
  const root=fs.mkdtempSync(path.join(os.tmpdir(),'localchat-lifetime-')),owner=spawn(process.execPath,['-e','setInterval(()=>{},1000)'],{windowsHide:true,stdio:'ignore'}),server=spawn(process.execPath,[path.join(__dirname,'../bridge/server.cjs'),'--port','0','--zotero-pid',String(owner.pid)],{env:{...process.env,LOCALAPPDATA:root,USERPROFILE:root,HOME:root},windowsHide:true,stdio:'ignore'});
  const finished=new Promise(resolve=>server.once('exit',code=>resolve(code)));t.after(async()=>{if(owner.exitCode===null)owner.kill();if(server.exitCode===null)server.kill();await finished;for(let i=0;i<20;i++){try{fs.rmSync(root,{recursive:true,force:true});break;}catch{await wait(100);}}});
  const file=path.join(root,'.zotero-localchat','endpoint.json');for(let i=0;i<100&&!fs.existsSync(file);i++)await wait(40);assert.ok(fs.existsSync(file));const u=new URL(JSON.parse(fs.readFileSync(file,'utf8')).url),headers={'X-Mirror-Token':u.hash.slice(1),'Content-Type':'application/json'};
  assert.equal((await fetch(u.origin+'/api/status',{headers})).status,200);assert.equal((await fetch(u.origin+'/api/owner',{method:'POST',body:JSON.stringify({pid:owner.pid})})).status,403);assert.equal((await fetch(u.origin+'/api/owner',{method:'POST',headers,body:JSON.stringify({pid:owner.pid})})).status,200);
  owner.kill();let timeout;try{assert.equal(await Promise.race([finished,new Promise((_,reject)=>{timeout=setTimeout(()=>reject(Error('Bridge outlived Zotero')),7000);})]),0);}finally{clearTimeout(timeout);}assert.equal(fs.existsSync(file),false);
});
