/* All network traffic from this page stays on the authenticated loopback bridge. */
const $=id=>document.getElementById(id),token=location.hash.slice(1),headers={'X-Mirror-Token':token};
let context=new URLSearchParams(location.search).get('context'),busy=false,ready=false,info,queued=[],turns=[],power,sendPending=false;
const draftKey=()=>`localchat-draft:${info?.draftKey||context}`;
function status(text,error=false){$('status').textContent=text;$('status').classList.toggle('error',error);}
function lock(value){busy=value;$('send').disabled=value||!ready;$('model').disabled=value||!ready;$('power').disabled=value||!ready;for(const id of ['new','attach','reconnect'])$(id).disabled=value;}
async function api(route,data){const r=await fetch('/api/'+route,{method:data===undefined?'GET':'POST',headers:{...headers,'Content-Type':'application/json'},body:data===undefined?undefined:JSON.stringify(data)});const result=await r.json();if(!r.ok)throw Error(result.error||'本地连接失败');return result;}
function render(){const area=$('messages'),nearBottom=area.scrollHeight-area.scrollTop-area.clientHeight<90;area.replaceChildren();if(!turns.length){const empty=document.createElement('div');empty.className='empty';empty.textContent=info?.mode==='blank'?'今天想聊些什么？':'从这篇论文开始聊聊';area.append(empty);}for(const turn of turns){if(!['user','assistant'].includes(turn.role))continue;const el=document.createElement('article');el.className='message '+turn.role;el.setAttribute('aria-label',turn.role==='user'?'你':'ChatGPT');const parts=turn.text.split(/```[^\n]*\n([\s\S]*?)```/g);parts.forEach((text,i)=>{const node=document.createElement(i%2?'pre':'p');node.textContent=text;el.append(node);});area.append(el);}if(nearBottom)area.scrollTop=area.scrollHeight;}
function models(data){$('model').replaceChildren();for(const m of data.models){const o=document.createElement('option');o.value=m.name;o.textContent=m.name;o.selected=m.selected;o.disabled=!m.enabled;$('model').append(o);}power=data.power;$('powerLabel').hidden=!power;if(power){$('power').max=power.max;$('power').value=power.index;powerText(power.index,data.strength);} }
function powerText(index,fallback){const label=power?.options?.[index]?.label;$('powerText').textContent=label||fallback?.split(/[，,]/)[0]||`档位 ${Number(index)+1}`;$('power').setAttribute('aria-valuetext',$('powerText').textContent);$('powerLabel').title=power?.options?.map((o,i)=>`${i+1}: ${o.label}`).join(' · ')||fallback||'';}
async function connect(recover=false){lock(true);status('正在连接本机 App…');try{await api('reconnect',{});info=await api('context?id='+context);if(!$('prompt').value)$('prompt').value=localStorage.getItem(draftKey())||(info.excerpt?'请解释这段文字：\n\n'+info.excerpt:'');if(recover&&['uncertain','sending','generating'].includes(info.phase))info=await api('session/recover',{id:context});info=await api('session/open',{id:context});$('paper').textContent=info.mode==='paper'?info.title:'Paper · 空白聊天';$('paper').title=$('paper').textContent;turns=(await api('transcript?id='+context)).turns;render();models(await api('session/model',{id:context}));ready=true;status(info.uploaded?'已关联这篇论文 · 可继续提问、追加文件':info.mode==='paper'?'首次发送时附上 PDF':'空白聊天 · 不附带论文');if(sendPending&&info.phase==='ready'){sendPending=false;$('prompt').value='';localStorage.removeItem(draftKey());for(const f of queued)await api('upload/remove',{id:context,file:f.id});queued=[];files();}}catch(e){ready=false;status(e.message+'。可点击重连。',true);}finally{lock(false);}}
$('prompt').value=localStorage.getItem(draftKey())||'';$('prompt').oninput=()=>localStorage.setItem(draftKey(),$('prompt').value);
$('reconnect').onclick=()=>connect(true);
$('new').onclick=async()=>{if(busy)return;if(($('prompt').value.trim()||queued.length)&&!confirm('开始新聊天？当前输入会保留在原会话，未发送附件会移除。'))return;lock(true);try{for(const f of queued)await api('upload/remove',{id:context,file:f.id});queued=[];files();const c=await api('context',{mode:'blank'});context=c.id;const url=new URL(location.href);url.searchParams.set('context',context);history.replaceState(null,'',url);$('prompt').value='';sendPending=false;await connect();}catch(e){status(e.message,true);lock(false);}};
$('model').onchange=async()=>{lock(true);try{models(await api('session/config',{id:context,model:$('model').value}));status('模型已切换');}catch(e){status(e.message,true);}finally{lock(false);}};
$('power').oninput=()=>powerText($('power').value);
$('power').onchange=async()=>{if(busy)return;lock(true);try{models(await api('session/config',{id:context,index:Number($('power').value)}));status('强度已切换');}catch(e){status(e.message,true);}finally{lock(false);}};
$('power').addEventListener('wheel',e=>{if(e.ctrlKey)return;e.preventDefault();if(busy||!power)return;const next=Math.min(power.max,Math.max(0,Number($('power').value)+(e.deltaY<0?1:-1)));if(next===Number($('power').value))return;$('power').value=next;$('power').oninput();$('power').onchange();},{passive:false});
function files(){$('files').replaceChildren();for(const f of queued){const b=document.createElement('button');b.type='button';b.textContent=f.name+' ×';b.title='移除 '+f.name;b.onclick=async()=>{if(busy)return;try{await api('upload/remove',{id:context,file:f.id});queued=queued.filter(x=>x!==f);files();}catch(e){status(e.message,true);}};$('files').append(b);}}
async function addFiles(list){if(busy)return;lock(true);try{for(const f of list){if(queued.length>=8)throw Error('每次最多添加 8 个文件');status('正在接收附件：'+f.name);const r=await fetch('/api/upload?id='+context+'&name='+encodeURIComponent(f.name),{method:'POST',headers,body:f});const result=await r.json();if(!r.ok)throw Error(result.error);queued.push(result);files();}status('附件已准备好，点击发送后上传');}catch(e){status(e.message,true);}finally{lock(false);$('fileInput').value='';}}
$('attach').onclick=()=>$('fileInput').click();$('fileInput').onchange=()=>addFiles([...$('fileInput').files]);
for(const name of ['dragenter','dragover'])document.addEventListener(name,e=>{if([...e.dataTransfer.types].includes('Files')){e.preventDefault();document.body.classList.add('dragover');}});
document.addEventListener('dragleave',e=>{if(!e.relatedTarget)document.body.classList.remove('dragover');});document.addEventListener('drop',e=>{e.preventDefault();document.body.classList.remove('dragover');if(e.dataTransfer.files.length)addFiles([...e.dataTransfer.files]);});
$('prompt').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();$('composer').requestSubmit();}};
$('composer').onsubmit=async e=>{e.preventDefault();const text=$('prompt').value.trim();if(busy||!ready||!text)return;lock(true);sendPending=true;status('正在发送…');try{
  const r=await fetch('/api/session/send-stream',{method:'POST',headers:{...headers,'Content-Type':'application/json'},body:JSON.stringify({id:context,text,files:queued.map(f=>f.id)})});if(!r.ok)throw Error((await r.json()).error);
  let completed=false;await MirrorStream.read(r,event=>{if(event.type==='error')throw Error(event.error);if(event.type==='phase')status(event.text);if(event.type==='accepted')status('等待 ChatGPT 回复…');if(event.type==='snapshot'){turns=event.turns;render();status(event.generating?'正在回复…':'回复完成');}if(event.type==='complete'){completed=true;info=event.info;status(info.warning||'已完成 · 可继续提问');}});
  if(!completed)throw Error('连接中断，发送状态未确认；请点击重连，避免重复提问');sendPending=false;$('prompt').value='';localStorage.removeItem(draftKey());queued=[];files();
}catch(e){ready=false;status(e.message+'。输入已保留；点击重连确认原回答。',true);}finally{lock(false);}};
let zoom=Number(localStorage.getItem('localchat-zoom'))||1;function setZoom(n){zoom=Math.max(.8,Math.min(1.6,n));document.documentElement.style.setProperty('--size',(15*zoom)+'px');$('zoomReset').textContent=Math.round(zoom*100)+'%';localStorage.setItem('localchat-zoom',zoom);}setZoom(zoom);
document.addEventListener('wheel',e=>{if(e.ctrlKey){e.preventDefault();setZoom(zoom+(e.deltaY<0?.05:-.05));}},{passive:false});document.addEventListener('keydown',e=>{if(e.ctrlKey&&e.key==='0'){e.preventDefault();setZoom(1);}});$('zoomReset').onclick=()=>setZoom(1);
if(context)connect();else{status('请从 Zotero 侧栏打开 Local Chat',true);lock(false);}
